INSERT INTO DECK_TYPE(ID_DECK_TYPE,NAME) VALUES (1,'Normal');
INSERT INTO DECK_TYPE(ID_DECK_TYPE,NAME) VALUES (2,'Fibonacci');

INSERT INTO DECK_TYPE_VALUES(ID_DECK_TYPE,VALUE) VALUES (1,1);
INSERT INTO DECK_TYPE_VALUES(ID_DECK_TYPE,VALUE) VALUES (1,2);
INSERT INTO DECK_TYPE_VALUES(ID_DECK_TYPE,VALUE) VALUES (1,3);
INSERT INTO DECK_TYPE_VALUES(ID_DECK_TYPE,VALUE) VALUES (1,4);
INSERT INTO DECK_TYPE_VALUES(ID_DECK_TYPE,VALUE) VALUES (1,5);
INSERT INTO DECK_TYPE_VALUES(ID_DECK_TYPE,VALUE) VALUES (2,1);
INSERT INTO DECK_TYPE_VALUES(ID_DECK_TYPE,VALUE) VALUES (2,2);
INSERT INTO DECK_TYPE_VALUES(ID_DECK_TYPE,VALUE) VALUES (2,3);
INSERT INTO DECK_TYPE_VALUES(ID_DECK_TYPE,VALUE) VALUES (2,5);
INSERT INTO DECK_TYPE_VALUES(ID_DECK_TYPE,VALUE) VALUES (2,8);
INSERT INTO DECK_TYPE_VALUES(ID_DECK_TYPE,VALUE) VALUES (2,13);
INSERT INTO DECK_TYPE_VALUES(ID_DECK_TYPE,VALUE) VALUES (2,21);

COMMIT;
